line_length:
  warning: 150
  error: 2000
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
disabled_rules:
- implicit_getter
- trailing_whitespace
- function_parameter_count
- identifier_name
- multiple_closures_with_trailing_closure
- type_body_length
